POST http://localhost:3000/shorten HTTP/1.1
content-type: application/json

{
  "original_url": "https://timesofindia.indiatimes.com/technology/reviews/star-wars-outlaws-review-a-scoundrels-dream-warts-and-all/articleshow/113102382.cms"
}

